_core:
  default_config_hash: qZeaiLq06xBUfw-JNZtgetxUUMz-J8YCzw_LuhPrk2E
langcode: ru
page_title: 'Карта сайта'
path: sitemap
message:
  value: ''
  format: restricted_html
plugins:
  frontpage:
    base_plugin: frontpage
    enabled: false
    weight: -50
    settings:
      title: 'Front page'
      rss: /rss.xml
  'menu:main':
    base_plugin: menu
    enabled: true
    weight: -50
    settings:
      title: 'Главное меню'
      show_disabled: false
      menu_depth: 9
  'menu:account':
    base_plugin: menu
    enabled: false
    weight: -50
    settings:
      title: 'User account menu'
      show_disabled: false
      menu_depth: 9
  'menu:admin':
    base_plugin: menu
    enabled: false
    weight: -50
    settings:
      title: Администрирование
      show_disabled: false
      menu_depth: 9
  'menu:footer':
    base_plugin: menu
    enabled: false
    weight: -50
    settings:
      title: Подвал
      show_disabled: false
      menu_depth: 9
  'menu:tools':
    base_plugin: menu
    enabled: false
    weight: -50
    settings:
      title: Tools
      show_disabled: false
      menu_depth: 9
  'vocabulary:branches':
    base_plugin: vocabulary
    enabled: false
    weight: -50
    settings:
      title: 'Структурные подразделения'
      show_description: true
      show_count: true
      term_depth: 9
      term_count_threshold: 0
      customize_link: null
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: null
      enable_rss: true
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:document_types':
    base_plugin: vocabulary
    enabled: false
    weight: -50
    settings:
      title: 'Типы документов'
      show_description: true
      show_count: true
      term_depth: 9
      term_count_threshold: 0
      customize_link: null
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: null
      enable_rss: true
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:tags':
    base_plugin: vocabulary
    enabled: false
    weight: -50
    settings:
      title: Теги
      show_description: true
      show_count: true
      term_depth: 9
      term_count_threshold: 0
      customize_link: null
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: null
      enable_rss: true
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
include_css: false
